# Generated by Django 6.0.2 on 2026-02-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_tag_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entries/%Y/%m', verbose_name='Изображение'),
        ),
    ]
