# Generated by Django 6.0.2 on 2026-02-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
