# Generated by Django 6.0.2 on 2026-03-09 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_logs', to='journal.entry', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Лог записи',
                'verbose_name_plural': 'Логи записей',
                'ordering': ['-timestamp'],
            },
        ),
    ]
