# Generated by Django 6.0.2 on 2026-03-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_entrylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='entry_title',
            field=models.CharField(default='old_title', max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_logs', to='journal.entry', verbose_name='Запись'),
        ),
    ]
