# Generated by Django 6.0.2 on 2026-03-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_entry_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='changed_entry_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
