# Generated by Django 6.0.2 on 2026-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_entry_author_alter_entrylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя автора'),
        ),
    ]
