# Generated by Django 6.0.2 on 2026-04-06 10:58

from django.db import migrations
from pytils.translit import slugify as pytils_slugify


CATEGORIES = [
        'Test',
        'General',
        'Работа',
        'Личное',
        'Обучение',
        'Проблема',
        'Идея',
    ]


def create_categories(apps, schema_editor):
    Category = apps.get_model('journal', 'Category')
    
    for category in CATEGORIES:
        Category.objects.create(
            name=category,
            slug=pytils_slugify(category)
        )


def delete_categories(apps, schema_editor):
    Category = apps.get_model('journal', 'Category')

    for category in CATEGORIES:
        try:
            Category.objects.get(name=category).delete()
        except Category.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_alter_comment_author_name'),
    ]

    operations = [migrations.RunPython(create_categories, delete_categories)]
