# Generated by Django 6.0.2 on 2026-04-21 11:50

import journal.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_create_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=journal.tools.wrapper_upload_to, validators=[journal.tools.validate_img_size], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('downloaded', 'Downloaded')], max_length=10, verbose_name='Действие'),
        ),
    ]
