server {
    listen 80;
    # Слушаем входящие соединения на порту 80 (стандартный HTTP)
    server_name viking-san.ru;

    location /.well-known/acme-challenge/ {
        # ssl сертификаты отдаём напрямую
        root /var/www/certbot;
    }

    location / {
        # Перенаправляем все запросы на HTTPS
        return 301 https://$host$request_uri;
    }
}

server{
    listen 443 ssl;
    # слушать https трафик на 443 порту
    server_name viking-san.ru;

    ssl_certificate /etc/letsencrypt/live/viking-san.ru/fullchain.pem;
    # Путь к сертификату и цепочка доверия
    ssl_certificate_key /etc/letsencrypt/live/viking-san.ru/privkey.pem;
    # Путь к ключу сертификата, никому не показывать содержимое

    client_max_body_size 15M;
    # Максимальный размер тела запроса — 15MB
    # Nginx отклонит файлы тяжелее этого ещё до Django
    # В модели/форме значения обрабатываются мягче, через исключение в шаблоне, а nginx сильно жестче.

    location /static/ {
        # Статические файлы (CSS, JS, иконки) отдаём напрямую
        # Django вообще не участвует — nginx сам читает файлы из тома
        alias /app/staticfiles/;
        expires 30d;
        # Говорим браузеру кэшировать статику 30 дней
        # Логично — CSS и JS меняются редко
    }

    location /media/ {
        # Запросы на медиафайлы (картинки) проксируем в MinIO
        proxy_pass http://minio:9000/journal-media/;
        # Обрати внимание: /media/ в URL заменяется на /<bucket>/
        # Браузер просит:  /media/entries/2026/03/photo.jpg
        # MinIO получает:  /journal-media/entries/2026/03/photo.jpg

        proxy_set_header Host minio;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        # Все остальные запросы идут в Django (gunicorn)
        proxy_pass http://web:8000;

        proxy_set_header Host $host;
        # Передаём оригинальный заголовок Host — Django знает на каком домене работает

        proxy_set_header X-Real-IP $remote_addr;
        # Передаём реальный IP пользователя
        # Без этого Django будет видеть IP nginx'а вместо IP пользователя

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Цепочка IP если запрос прошёл через несколько прокси

        proxy_set_header X-Forwarded-Proto $scheme;
        # Передаём протокол (http/https) — Django использует это
        # для правильной генерации ссылок
    }
}